image: node0.10
script:
  - npm install
  - npm test
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
publish:
  npm:
    branch: master
    email: {{npm_drone_email}}
    username: {{npm_drone_username}}
    password: {{npm_drone_password}}
