apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: async-ext
  description: Extensions to the Node.js async library
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
